apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: goef
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goef
    app.kubernetes.io/part-of: byoc-app-gxmd
  name: goef
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: goef
status:
  loadBalancer: {}
